using ChronoSim
using Documenter
using Literate

# Check command line arguments first
use_pdf = "--pdf" in ARGS

# Only load DocumenterMermaid for HTML format
if !use_pdf
    using DocumenterMermaid
end

# If you want to see this in LiveServer instead of on disk use:
# julia --project=docs -e 'using LiveServer; serve(dir="docs/build")'

# Usage:
# julia --project=docs docs/make.jl           # Build HTML documentation  
# julia --project=docs docs/make.jl --pdf     # Build PDF documentation
# julia --project=docs docs/make.jl --fresh   # Regenerate Literate files

DocMeta.setdocmeta!(ChronoSim, :DocTestSetup, :(using ChronoSim); recursive=true)

# Check command line arguments
fresh = "--fresh" in ARGS

# Function to process markdown files generated by Literate
function postprocess_markdown(content)
    # Adjust image paths to point to the literate subdirectory
    content = replace(content, r"!\[([^\]]*)\]\(([^)]+)\.png\)" => s"![\1](literate/\2.png)")
    return content
end

# Process Literate files if any exist in the future
literate_dir = joinpath(@__DIR__, "literate")
src_dir = joinpath(@__DIR__, "src")

# Create literate output directory if it doesn't exist
if !isdir(literate_dir)
    mkdir(literate_dir)
end

# Process Literate files
literate_src_dir = joinpath(@__DIR__, "literate_src")
if isdir(literate_src_dir)
    jlfiles = [f for f in readdir(literate_src_dir) if endswith(f, ".jl")]
else
    jlfiles = []
end
for readfile in jlfiles
    input_file = joinpath(literate_src_dir, readfile)
    output_file = joinpath(src_dir, replace(readfile, ".jl" => ".md"))
    if fresh || !isfile(output_file) || mtime(input_file) > mtime(output_file)
        println("Processing Literate file: $readfile")
        Literate.markdown(input_file, src_dir; postprocess=postprocess_markdown, execute=false)

        # Move any generated images to the literate subdirectory
        for img_file in readdir(src_dir)
            if endswith(img_file, ".png") ||
                endswith(img_file, ".jpg") ||
                endswith(img_file, ".svg")
                src_path = joinpath(src_dir, img_file)
                dst_path = joinpath(literate_dir, img_file)
                if isfile(src_path)
                    mv(src_path, dst_path; force=true)
                end
            end
        end
    end
end

# Choose format based on command line argument
doc_format = if use_pdf
    Documenter.LaTeX()
else
    Documenter.HTML(;
        canonical="https://adolgert.github.io/ChronoSim.jl",
        # Turn off pretty urls because they link to directories not files
        # and that doesn't work for browsers looking at local directories.
        prettyurls=get(ENV, "CI", nothing) == "true",
        edit_link="main",
        assets=["assets/custom.css"],
    )
end

makedocs(;
    modules=[ChronoSim],
    authors="Andrew Dolgert <github@dolgert.com>",
    sitename="ChronoSim.jl",
    format=doc_format,
    pages=[
        "Home" =>
            ["index.md", "Why Not Hand Made" => "not_chrono.md", "What It Does" => "whatitis.md"],
        "Examples" => ["Getting Started" => "getting_started.md"],
        "Manual" => [
            "Simulation State" => "simulation_state.md",
            "Category of Simulation" => "categorize.md",
        ],
        "Reference" => "reference.md",
        "Development" => [
            "Plan" => "plan.md",
            "Event Updates" => "event_update.md",
            "Architecture" => "architecture_diagram.md",
        ],
    ],
    warnonly=true,
    doctest=false,
)

# Only deploy for HTML format (not PDF)
if !use_pdf
    deploydocs(; repo="github.com/adolgert/ChronoSim.jl", devbranch="main")
end
