using ChronoSim
using Documenter
using Literate

# Check command line arguments first
use_pdf = "--pdf" in ARGS

# Only load DocumenterMermaid for HTML format
if !use_pdf
    using DocumenterMermaid
end

# If you want to see this in LiveServer instead of on disk use:
# julia --project=docs -e 'using LiveServer; serve(dir="docs/build")'

# Usage:
# julia --project=docs docs/make.jl           # Build HTML documentation  
# julia --project=docs docs/make.jl --pdf     # Build PDF documentation
# julia --project=docs docs/make.jl --fresh   # Regenerate Literate files

DocMeta.setdocmeta!(ChronoSim, :DocTestSetup, :(using ChronoSim); recursive=true)

# Check command line arguments
fresh = "--fresh" in ARGS

# Function to process markdown files generated by Literate
function postprocess_markdown(content)
    # Adjust image paths to point to the literate subdirectory
    content = replace(content, r"!\[([^\]]*)\]\(([^)]+)\.png\)" => s"![\1](literate/\2.png)")
    return content
end

# Process Literate files if any exist in the future
literate_dir = joinpath(@__DIR__, "literate")
src_dir = joinpath(@__DIR__, "src")

# Create literate output directory if it doesn't exist
if !isdir(literate_dir)
    mkdir(literate_dir)
end

# Process Literate files
literate_src_dir = joinpath(@__DIR__, "literate_src")
if isdir(literate_src_dir)
    jlfiles = [f for f in readdir(literate_src_dir) if endswith(f, ".jl")]
else
    jlfiles = []
end
# Files whose generated markdown must be fully static: their code fences are
# plain ` ```julia ` blocks that Documenter never executes (no `@example`
# blocks). Use this for pages that demonstrate heavy dependencies that are not
# in `docs/Project.toml`; they are run and asserted separately (see, e.g.,
# `docs/calibration/` for `statistical_calibration.jl`).
static_literate = Set(["statistical_calibration.jl"])
for readfile in jlfiles
    input_file = joinpath(literate_src_dir, readfile)
    output_file = joinpath(src_dir, replace(readfile, ".jl" => ".md"))
    if fresh || !isfile(output_file) || mtime(input_file) > mtime(output_file)
        println("Processing Literate file: $readfile")
        if readfile in static_literate
            Literate.markdown(
                input_file, src_dir;
                postprocess=postprocess_markdown, execute=false,
                codefence=("````julia" => "````"),
            )
        else
            Literate.markdown(
                input_file, src_dir; postprocess=postprocess_markdown, execute=false,
            )
        end

        # Move any generated images to the literate subdirectory
        for img_file in readdir(src_dir)
            if endswith(img_file, ".png") ||
                endswith(img_file, ".jpg") ||
                endswith(img_file, ".svg")
                src_path = joinpath(src_dir, img_file)
                dst_path = joinpath(literate_dir, img_file)
                if isfile(src_path)
                    mv(src_path, dst_path; force=true)
                end
            end
        end
    end
end

# Choose format based on command line argument
doc_format = if use_pdf
    Documenter.LaTeX()
else
    Documenter.HTML(;
        canonical="https://computingkitchen.com/ChronoSim.jl",
        # Turn off pretty urls because they link to directories not files
        # and that doesn't work for browsers looking at local directories.
        prettyurls=get(ENV, "CI", nothing) == "true",
        edit_link="main",
        assets=["assets/custom.css"],
        # reference.md is a single autodocs page over the whole package; the
        # adoption milestones grew it past Documenter's 200 KiB default.
        size_threshold=512 * 2^10,
        size_threshold_warn=300 * 2^10,
    )
end

makedocs(;
    modules=[ChronoSim],
    authors="Andrew Dolgert <github@dolgert.com>",
    sitename="ChronoSim.jl",
    format=doc_format,
    pages=[
        "Home" => [
            "index.md",
            "intro.md",
            "Why Not Hand Made" => "not_chrono.md",
            "What It Does" => "whatitis.md",
        ],
        "Examples" => [
            "Getting Started" => "getting_started.md",
            "Build an Elevator" => "elevator_tutorial.md",
        ],
        "Manual" => [
            "Simulation State" => ["observedphysical.md", "observedmacro.md", "customstate.md"],
            "Events" => "events.md",
            "Generators" => "generators.md",
            "Parameters and Differentiation" => "parameters.md",
            "Records and the Effect Check" => "minimal_records.md",
            "Coupling and Memory Declarations" => "declarations.md",
            "Cloning and Branching" => "cloning.md",
            "Randomness and Reproducibility" => "randomness.md",
        ],
        "Reference" => [
            "API" => "reference.md",
            "The Framework Guarantees" => "guarantees.md",
        ],
        "Debugging & Verification" => [
            "Overview" => "debugging_verification_overview.md",
            "Evaluating a Trace" => "trace_evaluation.md",
            "Calibrating from an Event Log" => "statistical_calibration.md",
            "Recording & Replaying" => "record_replay.md",
            "Declaring Invariants" => "invariants.md",
            "Debugging a Simulation" => "debugging.md",
            "Static Effect Analysis" => "effect_analysis.md",
            "Linting a Model" => "lint_footprints.md",
            "Model Checking a Simulation" => "model_checking.md",
            "Runbook" => "runbook.md",
        ],
        "Development" => [
            "How the System Fits Together" => "estimator_architecture.md",
            "Migration Notes" => "migration.md",
            "State Contract" => "state_contract.md",
            "Derivation Internals" => "derivation_internals.md",
            "Where ChronoSim Fits" => "categorize.md",
            "Plan" => "plan.md",
            "Event Updates" => "event_update.md",
            "Architecture" => "architecture_diagram.md",
        ],
    ],
    warnonly=true,
    doctest=false,
)

# Only deploy for HTML format (not PDF)
if !use_pdf
    deploydocs(; repo="github.com/adolgert/ChronoSim.jl", devbranch="main")
end
